export const HISTORY_LOADING = "HISTORY_LOADING";
export const HISTORY_FAILED = "HISTORY_FAILED";
export const ADD_HISTORY = "ADD_HISTORY";

export const MENU_LOADING = "MENU_LOADING";
export const MENU_FAILED = "MENU_FAILED";
export const ADD_MENU = "ADD_MENU";

export const INGREDIENT_LOADING = "INGREDIENT_LOADING";
export const INGREDIENT_FAILED = "INGREDIENT_FAILED";
export const ADD_INGREDIENT = "ADD_INGREDIENT";